/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedAdminLayoutRouteRouteImport } from './routes/_protected/_admin-layout/route'
import { Route as ProtectedCreateWorkspaceRouteImport } from './routes/_protected/create-workspace'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminLayoutdashboardIndexRouteImport } from './routes/_protected/_admin-layout/(dashboard)/index'
import { Route as ProtectedAdminLayoutdashboardTestRouteImport } from './routes/_protected/_admin-layout/(dashboard)/test'
import { Route as ProtectedAdminLayoutAccountIndexRouteImport } from './routes/_protected/_admin-layout/account/index'
import { Route as ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRouteImport } from './routes/_protected/_admin-layout/workspace/$workspaceId/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminLayoutRouteRoute =
  ProtectedAdminLayoutRouteRouteImport.update({
    id: '/_admin-layout',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCreateWorkspaceRoute =
  ProtectedCreateWorkspaceRouteImport.update({
    id: '/create-workspace',
    path: '/create-workspace',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminLayoutdashboardIndexRoute =
  ProtectedAdminLayoutdashboardIndexRouteImport.update({
    id: '/(dashboard)/',
    path: '/',
    getParentRoute: () => ProtectedAdminLayoutRouteRoute,
  } as any)
const ProtectedAdminLayoutdashboardTestRoute =
  ProtectedAdminLayoutdashboardTestRouteImport.update({
    id: '/(dashboard)/test',
    path: '/test',
    getParentRoute: () => ProtectedAdminLayoutRouteRoute,
  } as any)
const ProtectedAdminLayoutAccountIndexRoute =
  ProtectedAdminLayoutAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => ProtectedAdminLayoutRouteRoute,
  } as any)
const ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute =
  ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => ProtectedAdminLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedAdminLayoutdashboardIndexRoute
  '/create-workspace': typeof ProtectedCreateWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/test': typeof ProtectedAdminLayoutdashboardTestRoute
  '/account/': typeof ProtectedAdminLayoutAccountIndexRoute
  '/workspace/$workspaceId/': typeof ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedAdminLayoutdashboardIndexRoute
  '/create-workspace': typeof ProtectedCreateWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/test': typeof ProtectedAdminLayoutdashboardTestRoute
  '/account': typeof ProtectedAdminLayoutAccountIndexRoute
  '/workspace/$workspaceId': typeof ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/_admin-layout': typeof ProtectedAdminLayoutRouteRouteWithChildren
  '/_protected/create-workspace': typeof ProtectedCreateWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_admin-layout/(dashboard)/test': typeof ProtectedAdminLayoutdashboardTestRoute
  '/_protected/_admin-layout/(dashboard)/': typeof ProtectedAdminLayoutdashboardIndexRoute
  '/_protected/_admin-layout/account/': typeof ProtectedAdminLayoutAccountIndexRoute
  '/_protected/_admin-layout/workspace/$workspaceId/': typeof ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-workspace'
    | '/api/auth/$'
    | '/test'
    | '/account/'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-workspace'
    | '/api/auth/$'
    | '/test'
    | '/account'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/_admin-layout'
    | '/_protected/create-workspace'
    | '/api/auth/$'
    | '/_protected/_admin-layout/(dashboard)/test'
    | '/_protected/_admin-layout/(dashboard)/'
    | '/_protected/_admin-layout/account/'
    | '/_protected/_admin-layout/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_admin-layout': {
      id: '/_protected/_admin-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminLayoutRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create-workspace': {
      id: '/_protected/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof ProtectedCreateWorkspaceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_admin-layout/(dashboard)/': {
      id: '/_protected/_admin-layout/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminLayoutdashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminLayoutRouteRoute
    }
    '/_protected/_admin-layout/(dashboard)/test': {
      id: '/_protected/_admin-layout/(dashboard)/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ProtectedAdminLayoutdashboardTestRouteImport
      parentRoute: typeof ProtectedAdminLayoutRouteRoute
    }
    '/_protected/_admin-layout/account/': {
      id: '/_protected/_admin-layout/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAdminLayoutAccountIndexRouteImport
      parentRoute: typeof ProtectedAdminLayoutRouteRoute
    }
    '/_protected/_admin-layout/workspace/$workspaceId/': {
      id: '/_protected/_admin-layout/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof ProtectedAdminLayoutRouteRoute
    }
  }
}

interface ProtectedAdminLayoutRouteRouteChildren {
  ProtectedAdminLayoutdashboardTestRoute: typeof ProtectedAdminLayoutdashboardTestRoute
  ProtectedAdminLayoutdashboardIndexRoute: typeof ProtectedAdminLayoutdashboardIndexRoute
  ProtectedAdminLayoutAccountIndexRoute: typeof ProtectedAdminLayoutAccountIndexRoute
  ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute: typeof ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute
}

const ProtectedAdminLayoutRouteRouteChildren: ProtectedAdminLayoutRouteRouteChildren =
  {
    ProtectedAdminLayoutdashboardTestRoute:
      ProtectedAdminLayoutdashboardTestRoute,
    ProtectedAdminLayoutdashboardIndexRoute:
      ProtectedAdminLayoutdashboardIndexRoute,
    ProtectedAdminLayoutAccountIndexRoute:
      ProtectedAdminLayoutAccountIndexRoute,
    ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute:
      ProtectedAdminLayoutWorkspaceWorkspaceIdIndexRoute,
  }

const ProtectedAdminLayoutRouteRouteWithChildren =
  ProtectedAdminLayoutRouteRoute._addFileChildren(
    ProtectedAdminLayoutRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAdminLayoutRouteRoute: typeof ProtectedAdminLayoutRouteRouteWithChildren
  ProtectedCreateWorkspaceRoute: typeof ProtectedCreateWorkspaceRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminLayoutRouteRoute: ProtectedAdminLayoutRouteRouteWithChildren,
  ProtectedCreateWorkspaceRoute: ProtectedCreateWorkspaceRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
