admin:
  - changed-files:
      - any-glob-to-any-file:
          - apps/admin-web/**

auth:
  - changed-files:
      - any-glob-to-any-file:
          - apps/auth-web/**
          - packages/auth/**

marketing:
  - changed-files:
      - any-glob-to-any-file:
          - apps/marketing/**

storybook:
  - changed-files:
      - any-glob-to-any-file:
          - apps/storybook/**

widget:
  - changed-files:
      - any-glob-to-any-file:
          - apps/widget/**

ui:
  - changed-files:
      - any-glob-to-any-file:
          - packages/ui/**

db:
  - changed-files:
      - any-glob-to-any-file:
          - packages/db/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - docs/**

deps:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - bun.lock
          - '**/package.json'
